workspace:
  path: src/logglum
  base: /go
pipeline:
  build:
    image: golang:1.8-alpine
    pull: true
    commands:
      - go build 

  docker-commit:
    image: plugins/docker
    repo: comptel/logglum
    tags:
      - ${DRONE_BRANCH}
      - ${DRONE_COMMIT}
    when:
      event: push
      repo: comptelfwd/logglum
      
  docker-tag:
    image: plugins/docker
    repo: comptel/logglum
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
      repo: comptelfwd/logglum
      
  slack:
    image: plugins/slack
    channel: builds
    username: drone
    when:
      status:  [ failure, success ]
