clone:
  path: logglum
build:
  image: golang:1.7-alpine
  pull: true
  environment:
    - GOPATH=/drone/src/
  commands:
    - go build 
notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK
    channel: builds
    username: drone
  
publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: comptel/logglum
    tag:
      - $$BRANCH
      - $$COMMIT
    when:
      repo: comptelfwd/logglum
      event: push
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: comptel/logglum
    tag:
      - $$TAG
    when:
      repo: comptelfwd/logglum
      event: tag

